"""empty message

Revision ID: 16962ed4d88f
Revises: 1fdd2ec4d89c
Create Date: 2024-06-27 09:12:19.634570

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16962ed4d88f'
down_revision = '1fdd2ec4d89c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=50), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
