"""empty message

Revision ID: 1fdd2ec4d89c
Revises: ef4d03aac6c9
Create Date: 2024-06-25 12:51:28.255975

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1fdd2ec4d89c'
down_revision = 'ef4d03aac6c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoice', schema=None) as batch_op:
        batch_op.add_column(sa.Column('table_number', sa.Integer(), nullable=False))
        batch_op.drop_constraint('invoice_ibfk_2', type_='foreignkey')
        batch_op.drop_column('table_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoice', schema=None) as batch_op:
        batch_op.add_column(sa.Column('table_id', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('invoice_ibfk_2', 'table', ['table_id'], ['id'])
        batch_op.drop_column('table_number')

    # ### end Alembic commands ###
