"""empty message

Revision ID: 867dbe033031
Revises: 8c0d5dfc721c
Create Date: 2024-07-02 08:04:25.093448

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '867dbe033031'
down_revision = '8c0d5dfc721c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order') as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime, nullable=False, server_default=sa.func.now()))

    with op.batch_alter_table('table', schema=None) as batch_op:
        batch_op.drop_column('icon')
        batch_op.drop_column('position_x')
        batch_op.drop_column('position_y')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('position_y', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('position_x', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('icon', mysql.VARCHAR(length=250), nullable=False))

    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
