"""empty message

Revision ID: abdc3dfba512
Revises: 3765a4f2e4d6
Create Date: 2024-06-21 12:10:09.680276

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'abdc3dfba512'
down_revision = '3765a4f2e4d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###


    pass
    # ### end Alembic commands ###


def downgrade():
 
    pass

