"""Add position to tables

Revision ID: e5849c0bfa8e
Revises: 16962ed4d88f
Create Date: 2024-06-29 11:56:44.285308

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5849c0bfa8e'
down_revision = '16962ed4d88f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('position_x', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('position_y', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('table', schema=None) as batch_op:
        batch_op.drop_column('position_y')
        batch_op.drop_column('position_x')

    # ### end Alembic commands ###
