"""empty message

Revision ID: ef4d03aac6c9
Revises: f4e88ade260f
Create Date: 2024-06-23 20:21:45.201582

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef4d03aac6c9'
down_revision = 'f4e88ade260f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invoice_detail',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_invoice', sa.Integer(), nullable=False),
    sa.Column('id_product', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Float(), nullable=False),
    sa.Column('subtotal', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['id_invoice'], ['invoice.id'], ),
    sa.ForeignKeyConstraint(['id_product'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('table_session', schema=None) as batch_op:
        batch_op.add_column(sa.Column('table_number', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('table_session', schema=None) as batch_op:
        batch_op.drop_column('table_number')

    op.drop_table('invoice_detail')
    # ### end Alembic commands ###
