"""empty message

Revision ID: f4e88ade260f
Revises: abdc3dfba512
Create Date: 2024-06-23 12:13:06.837921

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f4e88ade260f'
down_revision = 'abdc3dfba512'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('invoice_detail')
    with op.batch_alter_table('invoice', schema=None) as batch_op:
        batch_op.add_column(sa.Column('restaurant_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('table_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('order_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('total_price', sa.Float(), nullable=False))
        batch_op.drop_constraint('invoice_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'order', ['order_id'], ['id'])
        batch_op.create_foreign_key(None, 'table', ['table_id'], ['id'])
        batch_op.create_foreign_key(None, 'restaurant', ['restaurant_id'], ['id'])
        batch_op.drop_column('date')
        batch_op.drop_column('id_table')
        batch_op.drop_column('summary')
        batch_op.drop_column('payment_method')

    with op.batch_alter_table('table', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'restaurant', ['restaurant_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('table', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('invoice', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_method', mysql.VARCHAR(length=50), nullable=False))
        batch_op.add_column(sa.Column('summary', mysql.FLOAT(), nullable=False))
        batch_op.add_column(sa.Column('id_table', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('date', mysql.DATETIME(), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('invoice_ibfk_1', 'table', ['id_table'], ['id'])
        batch_op.drop_column('total_price')
        batch_op.drop_column('order_id')
        batch_op.drop_column('table_id')
        batch_op.drop_column('restaurant_id')

    op.create_table('invoice_detail',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('id_invoice', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id_product', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('quantity', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('unit_price', mysql.FLOAT(), nullable=False),
    sa.Column('subtotal', mysql.FLOAT(), nullable=False),
    sa.ForeignKeyConstraint(['id_invoice'], ['invoice.id'], name='invoice_detail_ibfk_1'),
    sa.ForeignKeyConstraint(['id_product'], ['product.id'], name='invoice_detail_ibfk_2'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
