"""empty message

Revision ID: 260a85ae08dc
Revises: f9768b2c2853
Create Date: 2024-06-13 17:26:04.058169

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '260a85ae08dc'
down_revision = 'f9768b2c2853'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('menu', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.String(length=255), nullable=True))

    with op.batch_alter_table('table', schema=None) as batch_op:
        batch_op.alter_column('number',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=50),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('table', schema=None) as batch_op:
        batch_op.alter_column('number',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)

    with op.batch_alter_table('menu', schema=None) as batch_op:
        batch_op.drop_column('image')

    # ### end Alembic commands ###
