"""empty message

Revision ID: 3078cfda6e62
Revises: 9be02eb7c742
Create Date: 2024-06-17 21:52:16.778453

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3078cfda6e62'
down_revision = '9be02eb7c742'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # with op.batch_alter_table('order_item', schema=None) as batch_op:
    #     batch_op.add_column(sa.Column('category', sa.String(length=255), nullable=False))
    #     batch_op.add_column(sa.Column('completed', sa.Boolean(), nullable=False))
    pass
#     # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # with op.batch_alter_table('order_item', schema=None) as batch_op:
    #     batch_op.drop_column('completed')
    #     batch_op.drop_column('category')
    pass
#     # ### end Alembic commands ###
