"""empty message

Revision ID: 9be02eb7c742
Revises: 2ca61dc059ab
Create Date: 2024-06-17 00:22:52.610491

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9be02eb7c742'
down_revision = '2ca61dc059ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.alter_column('comment',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.drop_constraint('order_restaurant_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('order_table_id_fkey', type_='foreignkey')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.create_foreign_key('order_table_id_fkey', 'table', ['table_id'], ['id'])
        batch_op.create_foreign_key('order_restaurant_id_fkey', 'restaurant', ['restaurant_id'], ['id'])
        batch_op.alter_column('comment',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)

    # ### end Alembic commands ###
