"""empty message

Revision ID: a5f0934c1dbd
Revises: 
Create Date: 2024-07-05 12:13:54.542140

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a5f0934c1dbd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orderitem',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('menu_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('invoicedetail',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_invoice', sa.Integer(), nullable=False),
    sa.Column('id_product', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Float(), nullable=False),
    sa.Column('subtotal', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['id_invoice'], ['invoice.id'], ),
    sa.ForeignKeyConstraint(['id_product'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('producttable',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_session', sa.Integer(), nullable=False),
    sa.Column('id_product', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['id_product'], ['product.id'], ),
    sa.ForeignKeyConstraint(['id_session'], ['table_session.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('invoice_detail')
    op.drop_table('product_table')
    op.drop_table('order_item')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order_item',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('order_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('menu_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('quantity', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('price', mysql.FLOAT(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], name='order_item_ibfk_1'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product_table',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('id_session', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id_product', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('quantity', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('status', mysql.VARCHAR(length=50), nullable=False),
    sa.ForeignKeyConstraint(['id_product'], ['product.id'], name='product_table_ibfk_1'),
    sa.ForeignKeyConstraint(['id_session'], ['table_session.id'], name='product_table_ibfk_2'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('invoice_detail',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('id_invoice', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id_product', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('quantity', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('unit_price', mysql.FLOAT(), nullable=False),
    sa.Column('subtotal', mysql.FLOAT(), nullable=False),
    sa.ForeignKeyConstraint(['id_invoice'], ['invoice.id'], name='invoice_detail_ibfk_1'),
    sa.ForeignKeyConstraint(['id_product'], ['product.id'], name='invoice_detail_ibfk_2'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('producttable')
    op.drop_table('invoicedetail')
    op.drop_table('orderitem')
    # ### end Alembic commands ###
