"""empty message

Revision ID: f0482258c750
Revises: 65c294324e13
Create Date: 2024-06-23 10:29:47.165356

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f0482258c750'
down_revision = '65c294324e13'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # with op.batch_alter_table('invoice', schema=None) as batch_op:
    #     batch_op.drop_column('created_at')
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # with op.batch_alter_table('invoice', schema=None) as batch_op:
    #     batch_op.add_column(sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    pass
    # ### end Alembic commands ###
